// Code generated by goctl. DO NOT EDIT!
// Source: tools.proto

//go:generate mockgen -destination ./tools_mock.go -package toolsclient -source $GOFILE

package toolsclient

import (
	"context"

	"STFrontground-backend/rpc/tools/tools"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	MorseReq  = tools.MorseReq
	MorseResp = tools.MorseResp

	Tools interface {
		Morse(ctx context.Context, in *MorseReq) (*MorseResp, error)
	}

	defaultTools struct {
		cli zrpc.Client
	}
)

func NewTools(cli zrpc.Client) Tools {
	return &defaultTools{
		cli: cli,
	}
}

func (m *defaultTools) Morse(ctx context.Context, in *MorseReq) (*MorseResp, error) {
	client := tools.NewToolsClient(m.cli.Conn())
	return client.Morse(ctx, in)
}
