// Code generated by goctl. DO NOT EDIT!
// Source: tools.proto

//go:generate mockgen -destination ./tools_mock.go -package toolsclient -source $GOFILE

package toolsclient

import (
	"context"

	"STFrontground-backend/rpc/tools/tools"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	MorseResp    = tools.MorseResp
	QrCodeReq    = tools.QrCodeReq
	QrCodeResp   = tools.QrCodeResp
	Rgb2HexReq   = tools.Rgb2HexReq
	Rgb2HexResp  = tools.Rgb2HexResp
	GetStoryReq  = tools.GetStoryReq
	GetStoryResp = tools.GetStoryResp
	MorseReq     = tools.MorseReq

	Tools interface {
		Morse(ctx context.Context, in *MorseReq) (*MorseResp, error)
		QrCode(ctx context.Context, in *QrCodeReq) (*QrCodeResp, error)
		Rgb2Hex(ctx context.Context, in *Rgb2HexReq) (*Rgb2HexResp, error)
		Story(ctx context.Context, in *GetStoryReq) (*GetStoryResp, error)
	}

	defaultTools struct {
		cli zrpc.Client
	}
)

func NewTools(cli zrpc.Client) Tools {
	return &defaultTools{
		cli: cli,
	}
}

func (m *defaultTools) Morse(ctx context.Context, in *MorseReq) (*MorseResp, error) {
	client := tools.NewToolsClient(m.cli.Conn())
	return client.Morse(ctx, in)
}

func (m *defaultTools) QrCode(ctx context.Context, in *QrCodeReq) (*QrCodeResp, error) {
	client := tools.NewToolsClient(m.cli.Conn())
	return client.QrCode(ctx, in)
}

func (m *defaultTools) Rgb2Hex(ctx context.Context, in *Rgb2HexReq) (*Rgb2HexResp, error) {
	client := tools.NewToolsClient(m.cli.Conn())
	return client.Rgb2Hex(ctx, in)
}

func (m *defaultTools) Story(ctx context.Context, in *GetStoryReq) (*GetStoryResp, error) {
	client := tools.NewToolsClient(m.cli.Conn())
	return client.Story(ctx, in)
}
