// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"STFrontground-backend/rpc/user/internal/logic"
	"STFrontground-backend/rpc/user/internal/svc"
	"STFrontground-backend/rpc/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterReq) (*user.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) UserNameExit(ctx context.Context, in *user.UserNameExistReq) (*user.UserNameExistResp, error) {
	l := logic.NewUserNameExitLogic(ctx, s.svcCtx)
	return l.UserNameExit(in)
}

func (s *UserServer) UpdateToken(ctx context.Context, in *user.UpdateTokenReq) (*user.UpdateTokenResp, error) {
	l := logic.NewUpdateTokenLogic(ctx, s.svcCtx)
	return l.UpdateToken(in)
}
