// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Mobile   string `json:"mobile"`
	Token    string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	IsOK bool `json:"is_ok"`
}

type UserReply struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Mobile   string `json:"mobile"`
	JwtToken
}

type JwtToken struct {
	AccessToken  string `json:"accessToken,omitempty"`
	AccessExpire int64  `json:"accessExpire,omitempty"`
	RefreshAfter int64  `json:"refreshAfter,omitempty"`
}

type MorseReq struct {
	Str string `json:"str"`
}

type MorseResp struct {
	MorseStr string `json:"morse_str"`
}

type QrCodeReq struct {
	Str string `json:"str"`
}

type QrCodeResp struct {
	QrCodeStr string `json:"qrcode_str"`
}

type Rgb2HexReq struct {
	Str string `json:"str"`
}

type Rgb2HexResp struct {
	Rgb2HexStr string `json:"rgb2hex_str"`
}
