// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	api "STFrontground-backend/api/internal/handler/api"
	user "STFrontground-backend/api/internal/handler/user"
	"STFrontground-backend/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/ping",
				Handler: user.PingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/userNameExist",
				Handler: user.UserNameExistHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getVerificationCode",
				Handler: user.GetVerificationCodeHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Usercheck},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/morse",
					Handler: api.MorseHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/qrcode",
					Handler: api.QrcodeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/rgb2hex",
					Handler: api.Rgb2hexHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
