// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"STFrontground-backend/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/token",
				Handler: JwtHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/ping",
				Handler: pingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: registerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/morse",
				Handler: morseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/qrcode",
				Handler: qrcodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/rgb2hex",
				Handler: rgb2hexHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
