// Code generated by goctl. DO NOT EDIT!
// Source: tools.proto

package server

import (
	"context"

	"STFrontground-backend/rpc/tools/internal/logic"
	"STFrontground-backend/rpc/tools/internal/svc"
	"STFrontground-backend/rpc/tools/tools"
)

type ToolsServer struct {
	svcCtx *svc.ServiceContext
}

func NewToolsServer(svcCtx *svc.ServiceContext) *ToolsServer {
	return &ToolsServer{
		svcCtx: svcCtx,
	}
}

func (s *ToolsServer) Morse(ctx context.Context, in *tools.MorseReq) (*tools.MorseResp, error) {
	l := logic.NewMorseLogic(ctx, s.svcCtx)
	return l.Morse(in)
}

func (s *ToolsServer) QrCode(ctx context.Context, in *tools.QrCodeReq) (*tools.QrCodeResp, error) {
	l := logic.NewQrCodeLogic(ctx, s.svcCtx)
	return l.QrCode(in)
}

func (s *ToolsServer) Rgb2Hex(ctx context.Context, in *tools.Rgb2HexReq) (*tools.Rgb2HexResp, error) {
	l := logic.NewRgb2HexLogic(ctx, s.svcCtx)
	return l.Rgb2Hex(in)
}
